# -*- coding: utf-8 -*-
"""credibility_score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOdqJVnvQtXhkPQFWE5HRO-Va0hUjl_F
"""

def calculate_credibility(modules: dict, weights: dict = None) -> dict:
    # Default weights (adjust as needed)
    default_weights = {
        "fact_checker": 0.4,
        "similarity_checker": 0.25,
        "bias_detector": 0.15,
        "sentiment_analysis": 0.1,
        "diversity_score": 0.1   
    }

    if weights is None:
        weights = default_weights

    total_score = 0.0
    total_weight = 0.0
    breakdown = {}

    for module, result in modules.items():
        module_score = result.get("score", 0.0)
        weight = weights.get(module, 0.0)
        weighted_score = module_score * weight

        total_score += weighted_score
        total_weight += weight
        breakdown[module] = {
            "score": module_score,
            "weight": weight,
            "contribution": round(weighted_score, 3)
        }

    final_score = round(total_score / total_weight, 3) if total_weight else 0.0

    return {
        "final_score": final_score,
        "breakdown": breakdown,
        "explanation": f"Credibility score based on {len(modules)} modules."
    }